# Data Consolidation

## Datenimport

Als erstes müssen die Originaldatensätze eingelesen werden, damit wir diese manipulieren können.
Zunächst nehmen wir einen Abgleich der Daten aus den verschiedenen Daten vor und legen fest, was in welchem Datensatz angepasst, gelöscht oder umbenannt werden muss.

In [ ]:
import pandas as pd

In [ ]:
#from google.colab import files
#uploaded = files.upload() #Upload Data von Finder

In [ ]:
#Einlesen der Daten
df_tmdb_5000 = pd.read_csv('tmdb_5000_movies.csv')
screenplay_awards = pd.read_csv('screenplay_awards.csv')
df_titles = pd.read_csv('titles.csv')
netflix_titles = pd.read_csv('netflix_titles.csv')
movie_meta_data = pd.read_csv('movie_meta_data.csv')
credits = pd.read_csv('credits.csv')

##Vergleichen der Datensätze

In [ ]:
#Datentypen und Spaltenbezeichnungen vergleichen
df_tmdb_5000.dtypes

#To Do: Spalten entfernen: 'homepage','keywords', 'overview', 'popularity', 'release_date', 'revenue', 'spoken_languages', 'status', 'title', 'vote_count'
#       Spalten umbenennen: "original_title" und "vote_average"

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

In [ ]:
df_titles.dtypes

#To Do: Spalten entfernen: age_certification','seasons','type','release_year','tmdb_popularity'

id                       object
title                    object
type                     object
description              object
release_year              int64
age_certification        object
runtime                   int64
genres                   object
production_countries     object
seasons                 float64
imdb_id                  object
imdb_score              float64
imdb_votes              float64
tmdb_popularity         float64
tmdb_score              float64
dtype: object

In [ ]:
netflix_titles.dtypes

#To do's: Spalten umbenennen (country in production_countries, duration in runtime und 'min' weg, listed_in in genres, generell Leerzeichen durch _ ersetzen)
#         Spalten entfernen, die nicht relevant sind (show_id','date_added','rating', 'release_year)

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
movie_meta_data.dtypes

#To do's: Spalten umbenennen (Directors, imdb user rating, number of imdb user votes, countries)
#         Spalten entfernen, die nicht relevant sind (akas', 'year', 'metascore', 'opening weekend', 'script department', 'writers', 'casting directors', 'age restrict', 'keywords', 'synopsis')

imdbid                        int64
title                        object
akas                         object
year                          int64
metascore                     int64
imdb user rating              int64
number of imdb user votes     int64
awards                       object
opening weekend              object
producers                    object
budget                       object
script department            object
production companies         object
writers                      object
directors                    object
casting directors            object
cast                         object
countries                    object
age restrict                 object
plot                         object
plot outline                 object
keywords                     object
genres                       object
taglines                     object
synopsis                     object
dtype: object

In [ ]:
credits.dtypes

# To Do's: person_id entfernen, da nicht relevant

person_id     int64
id           object
name         object
character    object
role         object
dtype: object

In [ ]:
screenplay_awards.dtypes

# To Do's: Umbennen der Spalte Movie in title, damit die Spalten aller verwendeten Datensätze identisch bezeichnet sind
#          Anpassen der Werte in der title Spalte (Unterstrich und Ziffern entfernen)

movie                                                object
Academy Awards adapted screenplay                    object
Academy Awards original screenplay                   object
BAFTA nominations                                    object
Golden Globe Award for Best Screenplay               object
Writers Guild Awards Winners & Nominees 2020-2013    object
dtype: object

# Data Cleansing

## Cleaning tmdb_5000_movies.csv

### Überprüfen der Werte im Datensatz

In [ ]:
#Einlesen der Daten
df_tmdb_5000 = pd.read_csv('tmdb_5000_movies.csv')

In [ ]:
#Abbilden der Daten
df_tmdb_5000

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [ ]:
#Fehlende Werte überprüfen
df_tmdb_5000.isna().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [ ]:
#Fehlende Werte in Prozent
(df_tmdb_5000.isna().sum()/len(df_tmdb_5000)).apply('{0:.4%}'.format)

# --> "homepage" und "tagline" weisen große Lücken auf, die fehlenden Werte von "tagline" wollen wir aber bis zum Joinen im Datensatz lassen,
#um beim Joinen eventuell fehlende Werte verringern zu können, "homepage ist für unser Projekt nicht relevant und wird im nächstenn Schritt aus dem Datensatz entfernt"

budget                   0.0000%
genres                   0.0000%
homepage                64.3556%
id                       0.0000%
keywords                 0.0000%
original_language        0.0000%
original_title           0.0000%
overview                 0.0625%
popularity               0.0000%
production_companies     0.0000%
production_countries     0.0000%
release_date             0.0208%
revenue                  0.0000%
runtime                  0.0416%
spoken_languages         0.0000%
status                   0.0000%
tagline                 17.5724%
title                    0.0000%
vote_average             0.0000%
vote_count               0.0000%
dtype: object

In [ ]:
#Kontrollieren auf doppelte Zeilen
df_tmdb_5000.duplicated().sum()

#Da keine vorhanden, muss nichts entfernt werden

0

In [ ]:
#Statistische Eigenschaften des Datensatzes anzeigen lassen
df_tmdb_5000_clean.describe()

             budget             id      runtime  vote_average
count  4.803000e+03    4803.000000  4801.000000   4803.000000
mean   2.904504e+07   57165.484281   106.875859      6.092172
std    4.072239e+07   88694.614033    22.611935      1.194612
min    0.000000e+00       5.000000     0.000000      0.000000
25%    7.900000e+05    9014.500000    94.000000      5.600000
50%    1.500000e+07   14629.000000   103.000000      6.200000
75%    4.000000e+07   58610.500000   118.000000      6.800000
max    3.800000e+08  459488.000000   338.000000     10.000000

### Spalten aufbereiten

Wir entfernen alle Spalten, die nicht relevant für unser Projket sind. Bevor wir mit der Bereinigung gestartet haben, haben wir uns alle Datensätze angeschaut und miteinander verglichen. Dabei haben wir uns eine Liste erstellt, welche Spalten nicht relevant für unser Model sein werden. Außerdem haben wir notiert, welche Spalten umbenannt werden müssen bzw. welche Datentypen umgewandelt werden müssen, damit alle Datensätze identisch sind und gejoint werden können. Daher muss an dieser Stelle auch nur der "original title" behalten werden, da dieser auch in den anderen Datensätzen enthalten ist. Jedoch benennen wir die Spalte in "title" um, damit alle Spalten aller Datensätze gleich benannt sind. Die ursprüngliche Spalte "title" kann entfernt werden.

In [ ]:
#Entfernen von Spalten, die nicht gebraucht werden
df_tmdb_5000_clean = (df_tmdb_5000.
                      drop(['homepage','keywords', 'overview', 'popularity', 'release_date', 'revenue', 'spoken_languages', 'status', 'title', 'vote_count'], 1))

<ipython-input-56-c68057510854>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  drop(['homepage','keywords', 'overview', 'popularity', 'release_date', 'revenue', 'spoken_languages', 'status', 'title', 'vote_count'], 1))

### Datentypen anpassen

In [ ]:
#Datentypen prüfen
df_tmdb_5000_clean.dtypes

budget                    int64
genres                   object
id                        int64
original_language        object
original_title           object
production_companies     object
production_countries     object
runtime                 float64
tagline                  object
vote_average            float64
dtype: object

In [ ]:
#budget in object umwandeln
df_tmdb_5000_clean2 = df_tmdb_5000_clean.astype({'budget': object})

In [ ]:
#id in object umwandeln
df_tmdb_5000_clean3 = df_tmdb_5000_clean2.astype({'id': object})

In [ ]:
#Datentypen prüfen, ob nun korrekt
df_tmdb_5000_clean3.dtypes

budget                   object
genres                   object
id                       object
original_language        object
original_title           object
production_companies     object
production_countries     object
runtime                 float64
tagline                  object
vote_average            float64
dtype: object

In [ ]:
#Spalten umbenennen: "original_title" und "vote_average"
df_tmdb_5000_clean3.rename(columns={'original_title': 'title', 'vote_average': 'tmdb_score'}, inplace=True)

In [ ]:
#Überprüfen, ob alle columns nun korrekt heißen
df_tmdb_5000_clean3

,budget,genres,id,original_language,title,production_companies,production_countries,runtime,tagline,tmdb_score
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,en,Avatar,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",162.0,Enter the World of Pandora.,7.2
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,en,Pirates of the Caribbean: At World's End,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",169.0,"At the end of the world, the adventure begins.",6.9
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,en,Spectre,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",148.0,A Plan No One Escapes,6.3
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,en,The Dark Knight Rises,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",165.0,The Legend Ends,7.6
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,en,John Carter,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",132.0,"Lost in our world, found in another.",6.1
...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,es,El Mariachi,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",81.0,"He didn't come looking for trouble, but troubl...",6.6
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,en,Newlyweds,[],[],85.0,A newlywed couple's honeymoon is upended by th...,5.9
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,en,"Signed, Sealed, Delivered","[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",120.0,NaN,7.0
4801,0,[],126186,en,Shanghai Calling,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",98.0,A New Yorker in Shanghai,5.7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",25975,en,My Date with Drew,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",90.0,NaN,6.3

### Speichern des bereinigten Datensatzes

In [ ]:
#Speichern der gereinigten Daten als csv-Datei
df_tmdb_5000_clean3.to_csv("tmdb_5000_join.csv", index=False)

##Cleaning screenplay awards

### Überprüfen der Werte im Datensatz

In [ ]:
#Einlesen der Daten
screenplay_awards = pd.read_csv('screenplay_awards.csv')
#Anzeigen der Daten
screenplay_awards

,movie,Academy Awards adapted screenplay,Academy Awards original screenplay,BAFTA nominations,Golden Globe Award for Best Screenplay,Writers Guild Awards Winners & Nominees 2020-2013
0,A Tree Grows in Brooklyn_0038190,+,-,-,-,-
1,Winter s Bone_1399683,+,-,-,-,-
2,The Hustler_0054997,+,-,-,-,-
3,Leaving Las Vegas_0113627,+,-,+,-,-
4,Before Midnight_2209418,+,-,-,-,+
...,...,...,...,...,...,...
457,Deadpool_1431045,-,-,-,-,+
458,Looper_1276104,-,-,-,-,+
459,The Perks of Being a Wallflower_1659337,-,-,-,-,+
460,Kingsman Theory of Everything Foxcatcher_4682196,-,-,-,-,+
461,One Soldier s Story The Journey of American Sn...,-,-,-,-,+

In [ ]:
#Kontrollieren auf fehlende Werte
screenplay_awards.isna().sum()

movie                                                0
Academy Awards adapted screenplay                    0
Academy Awards original screenplay                   0
BAFTA nominations                                    0
Golden Globe Award for Best Screenplay               0
Writers Guild Awards Winners & Nominees 2020-2013    0
dtype: int64

In [ ]:
#Kontrollieren auf doppelte Zeilen
screenplay_awards.duplicated().sum()

#Keine Bereinigung notwendig, da keine fehlende Werte + Duplikate

0

In [ ]:
#Statistische Eigenschaften des Datensatzes anzeigen lassen
screenplay_awards.describe()

,movie,Academy Awards adapted screenplay,Academy Awards original screenplay,BAFTA nominations,Golden Globe Award for Best Screenplay,Writers Guild Awards Winners & Nominees 2020-2013
count,462,462,462,462,462,462
unique,462,2,2,2,2,2
top,A Tree Grows in Brooklyn_0038190,-,-,+,-,-
freq,1,262,294,251,268,384

### Datentypen anpassen

In [ ]:
#Prüfen der Datentypen mit den anderen Datensätzen übereinstimmen für die Spalten, die als key verwendet werden sollen
screenplay_awards.dtypes

movie                                                object
Academy Awards adapted screenplay                    object
Academy Awards original screenplay                   object
BAFTA nominations                                    object
Golden Globe Award for Best Screenplay               object
Writers Guild Awards Winners & Nominees 2020-2013    object
dtype: object

### Spalten aufbereiten

In [ ]:
#Umbennen der Spalte Movie in title, damit die Spalten aller verwendeten Datensätze identisch bezeichnet sind
screenplay_awards = screenplay_awards.rename(columns={"movie": "title"})

In [ ]:
#Anpassen der Werte in der title Spalte (Unterstrich und Ziffern entfernen)
screenplay_awards.title = screenplay_awards.title.str.split('_').str[0]

In [ ]:
#Überprüfen, ob Datensatz nun bereit zum joinen ist
screenplay_awards

,title,Academy Awards adapted screenplay,Academy Awards original screenplay,BAFTA nominations,Golden Globe Award for Best Screenplay,Writers Guild Awards Winners & Nominees 2020-2013
0,A Tree Grows in Brooklyn,+,-,-,-,-
1,Winter s Bone,+,-,-,-,-
2,The Hustler,+,-,-,-,-
3,Leaving Las Vegas,+,-,+,-,-
4,Before Midnight,+,-,-,-,+
...,...,...,...,...,...,...
457,Deadpool,-,-,-,-,+
458,Looper,-,-,-,-,+
459,The Perks of Being a Wallflower,-,-,-,-,+
460,Kingsman Theory of Everything Foxcatcher,-,-,-,-,+
461,One Soldier s Story The Journey of American Sn...,-,-,-,-,+

### Speichern des bereinigten Datensatzes

In [ ]:
#Speichern des Datensatzes als csv Datei
screenplay_awards.to_csv("screenplay_awards_join.csv")

## Cleaning titles.csv

In [ ]:
#Einlesen der Daten
df_titles = pd.read_csv('/content/titles.csv')
#Abbilden der Daten
df_titles.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,114,"['drama', 'crime']",['US'],NaN,tt0075314,8.2,808582.0,40.965,8.179
2,tm154986,Deliverance,MOVIE,Intent on seeing the Cahulawassee River before...,1972,R,109,"['drama', 'action', 'thriller', 'european']",['US'],NaN,tt0068473,7.7,107673.0,10.010,7.300
3,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['fantasy', 'action', 'comedy']",['GB'],NaN,tt0071853,8.2,534486.0,15.461,7.811
4,tm120801,The Dirty Dozen,MOVIE,12 American military prisoners in World War II...,1967,NaN,150,"['war', 'action']","['GB', 'US']",NaN,tt0061578,7.7,72662.0,20.398,7.600

### Spalten aufbereiten

In [ ]:
#Entfernen der Spalten, diese unrelevant für unser Projekt sind
df_titles_clean = df_titles.drop(columns=['age_certification','seasons','type','release_year','tmdb_popularity'])

In [ ]:
#Prüfen, ob Daten nun so wie benötigt sind
df_titles_clean.head()

,id,title,description,runtime,genres,production_countries,imdb_id,imdb_score,imdb_votes,tmdb_score
0,ts300399,Five Came Back: The Reference Films,This collection includes 12 World War II-era p...,51,['documentation'],['US'],NaN,NaN,NaN,NaN
1,tm84618,Taxi Driver,A mentally unstable Vietnam War veteran works ...,114,"['drama', 'crime']",['US'],tt0075314,8.2,808582.0,8.179
2,tm154986,Deliverance,Intent on seeing the Cahulawassee River before...,109,"['drama', 'action', 'thriller', 'european']",['US'],tt0068473,7.7,107673.0,7.300
3,tm127384,Monty Python and the Holy Grail,"King Arthur, accompanied by his squire, recrui...",91,"['fantasy', 'action', 'comedy']",['GB'],tt0071853,8.2,534486.0,7.811
4,tm120801,The Dirty Dozen,12 American military prisoners in World War II...,150,"['war', 'action']","['GB', 'US']",tt0061578,7.7,72662.0,7.600

In [ ]:
#Spalte tmdb_score auf eine Nachkommastelle runden
df_titles_clean['tmdb_score']=df_titles_clean['tmdb_score'].round(1)
#Überprüfung
df_titles_clean

,id,title,description,runtime,genres,production_countries,imdb_id,imdb_score,imdb_votes,tmdb_score
0,ts300399,Five Came Back: The Reference Films,This collection includes 12 World War II-era p...,51,['documentation'],['US'],NaN,NaN,NaN,NaN
1,tm84618,Taxi Driver,A mentally unstable Vietnam War veteran works ...,114,"['drama', 'crime']",['US'],tt0075314,8.2,808582.0,8.2
2,tm154986,Deliverance,Intent on seeing the Cahulawassee River before...,109,"['drama', 'action', 'thriller', 'european']",['US'],tt0068473,7.7,107673.0,7.3
3,tm127384,Monty Python and the Holy Grail,"King Arthur, accompanied by his squire, recrui...",91,"['fantasy', 'action', 'comedy']",['GB'],tt0071853,8.2,534486.0,7.8
4,tm120801,The Dirty Dozen,12 American military prisoners in World War II...,150,"['war', 'action']","['GB', 'US']",tt0061578,7.7,72662.0,7.6
...,...,...,...,...,...,...,...,...,...,...
5845,tm1014599,Fine Wine,A beautiful love story that can happen between...,100,"['romance', 'drama']",['NG'],tt13857480,6.8,45.0,NaN
5846,tm898842,C/O Kaadhal,A heart warming film that explores the concept...,134,['drama'],[],tt11803618,7.7,348.0,NaN
5847,tm1059008,Lokillo,A controversial TV host and comedian who has b...,90,['comedy'],['CO'],tt14585902,3.8,68.0,6.3
5848,tm1035612,Dad Stop Embarrassing Me - The Afterparty,"Jamie Foxx, David Alan Grier and more from the...",37,[],['US'],NaN,NaN,NaN,10.0
5849,ts271048,Mighty Little Bheem: Kite Festival,"With winter behind them, Bheem and his townspe...",7,"['family', 'animation', 'comedy']",[],tt13711094,7.8,18.0,10.0

### Überprüfen der Werte im Datensatz

In [ ]:
#Überprüfung Duplikate
df_titles_clean.duplicated().sum()

0

In [ ]:
#Überprüfng fehlende Werte
df_titles_clean.isna().sum()

id                        0
title                     1
description              18
runtime                   0
genres                    0
production_countries      0
imdb_id                 403
imdb_score              482
imdb_votes              498
tmdb_score              311
dtype: int64

In [ ]:
#Fehlende Werte in Prozent
(df_titles_clean.isna().sum()/len(df_titles_clean)).apply('{0:.4%}'.format)

id                      0.0000%
title                   0.0171%
description             0.3077%
runtime                 0.0000%
genres                  0.0000%
production_countries    0.0000%
imdb_id                 6.8889%
imdb_score              8.2393%
imdb_votes              8.5128%
tmdb_score              5.3162%
dtype: object

### Datentypen anpassen

In [ ]:
#Datentypen anzeigen lassen
df_titles_clean.dtypes

id                       object
title                    object
description              object
runtime                   int64
genres                   object
production_countries     object
imdb_id                  object
imdb_score              float64
imdb_votes              float64
tmdb_score              float64
dtype: object

In [ ]:
#Runtime in float umwandeln
df_titles_clean2 = df_titles_clean.astype({'runtime': float})

#Überprüfen, ob Datentyp nun korrekt
df_titles_clean2.dtypes

id                       object
title                    object
description              object
runtime                 float64
genres                   object
production_countries     object
imdb_id                  object
imdb_score              float64
imdb_votes              float64
tmdb_score              float64
dtype: object

### Speichern des bereinigten Datensatzes

In [ ]:
#Abspeichern als csv.Datei
df_titles_clean2.to_csv("titles_join.csv", index=False)

## Cleaning netflix_titles.csv

### Überprüfung der Werte im Datensatz

In [ ]:
#Einlesen der Daten
Netflix_Filme = pd.read_csv('/content/netflix_titles.csv')

In [ ]:
#Anzeigen der Daten
Netflix_Filme.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

import altair as alt
from google.colab import autoviz
df_8796431372662020818 = autoviz.get_registered_df('df_8796431372662020818')

def histogram(df, colname, maxbins=20, width=100, height=50):
  return (alt.Chart(df).mark_bar()
          .encode(
              x=alt.X(colname, bin=alt.Bin(maxbins=maxbins)),
              y=alt.Y('count()', axis=alt.Axis(title='count')),
          )
          .properties(width=width, height=height))  #  Pixels.

chart = histogram(df_8796431372662020818, *['index'], **{})
chart

import altair as alt
from google.colab import autoviz
df_3884676402964301672 = autoviz.get_registered_df('df_3884676402964301672')

def histogram(df, colname, maxbins=20, width=100, height=50):
  return (alt.Chart(df).mark_bar()
          .encode(
              x=alt.X(colname, bin=alt.Bin(maxbins=maxbins)),
              y=alt.Y('count()', axis=alt.Axis(title='count')),
          )
          .properties(width=width, height=height))  #  Pixels.

chart = histogram(df_3884676402964301672, *['release_year'], **{})
chart

import altair as alt
from google.colab import autoviz
df_4624682306391497693 = autoviz.get_registered_df('df_4624682306391497693')

def value_plot(df, y, sort_ascending=False, width=100, height=50):
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  return (alt.Chart(df.reset_index()).mark_line()
          .encode(x=alt.X('index', title=''), y=alt.X(y, title='value'))
          .properties(width=width, height=height, title=y))

chart = value_plot(df_4624682306391497693, *['index'], **{})
chart

import altair as alt
from google.colab import autoviz
df_6733642260426635626 = autoviz.get_registered_df('df_6733642260426635626')

def value_plot(df, y, sort_ascending=False, width=100, height=50):
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  return (alt.Chart(df.reset_index()).mark_line()
          .encode(x=alt.X('index', title=''), y=alt.X(y, title='value'))
          .properties(width=width, height=height, title=y))

chart = value_plot(df_6733642260426635626, *['release_year'], **{})
chart

import altair as alt
from google.colab import autoviz
df_1693127756340109081 = autoviz.get_registered_df('df_1693127756340109081')

def categorical_histogram(df, colname, width=100, height=50, colormap='dark2'):
  chart_data = df[colname].value_counts().reset_index(name='count')
  return (alt.Chart(chart_data).mark_bar()
          .encode(
              x='count', y=alt.Y('index', title=''),
              color=alt.Color(
                  'index', scale=alt.Scale(scheme=colormap), legend=None))
          .properties(width=width, height=height, title=colname))  # Pixels.

chart = categorical_histogram(df_1693127756340109081, *['show_id'], **{})
chart

import altair as alt
from google.colab import autoviz
df_2434491686067917113 = autoviz.get_registered_df('df_2434491686067917113')

def categorical_histogram(df, colname, width=100, height=50, colormap='dark2'):
  chart_data = df[colname].value_counts().reset_index(name='count')
  return (alt.Chart(chart_data).mark_bar()
          .encode(
              x='count', y=alt.Y('index', title=''),
              color=alt.Color(
                  'index', scale=alt.Scale(scheme=colormap), legend=None))
          .properties(width=width, height=height, title=colname))  # Pixels.

chart = categorical_histogram(df_2434491686067917113, *['type'], **{})
chart

import altair as alt
from google.colab import autoviz
df_8325436555467291225 = autoviz.get_registered_df('df_8325436555467291225')

def categorical_histogram(df, colname, width=100, height=50, colormap='dark2'):
  chart_data = df[colname].value_counts().reset_index(name='count')
  return (alt.Chart(chart_data).mark_bar()
          .encode(
              x='count', y=alt.Y('index', title=''),
              color=alt.Color(
                  'index', scale=alt.Scale(scheme=colormap), legend=None))
          .properties(width=width, height=height, title=colname))  # Pixels.

chart = categorical_histogram(df_8325436555467291225, *['title'], **{})
chart

import altair as alt
from google.colab import autoviz
df_5157084881371778874 = autoviz.get_registered_df('df_5157084881371778874')

def categorical_histogram(df, colname, width=100, height=50, colormap='dark2'):
  chart_data = df[colname].value_counts().reset_index(name='count')
  return (alt.Chart(chart_data).mark_bar()
          .encode(
              x='count', y=alt.Y('index', title=''),
              color=alt.Color(
                  'index', scale=alt.Scale(scheme=colormap), legend=None))
          .properties(width=width, height=height, title=colname))  # Pixels.

chart = categorical_histogram(df_5157084881371778874, *['director'], **{})
chart

import altair as alt
from google.colab import autoviz
df_2512881391920897060 = autoviz.get_registered_df('df_2512881391920897060')

def linked_scatter_plots(
    df, colname_pairs, color='steelblue', deselected_color='lightgray',
    opacity=0.8, deselected_opacity=0.4, width=150, height=150):
  interval = alt.selection_interval()
  scatter = (alt.Chart(df).mark_circle()
             .encode(
                 color=alt.condition(
                     interval, alt.value(color), alt.value(deselected_color)),
                 opacity=alt.condition(
                     interval, alt.value(opacity),
                     alt.value(deselected_opacity)))
             .properties(
                 selection=interval, width=width, height=height))
  return alt.hconcat(*[scatter.encode(x=x, y=y) for x, y in colname_pairs])

chart = linked_scatter_plots(df_2512881391920897060, *[[['index', 'release_year']]], **{})
chart

import altair as alt
from google.colab import autoviz
df_6200309758917209239 = autoviz.get_registered_df('df_6200309758917209239')

def heatmap(df, x_colname, y_colname):
  return (alt.Chart(df).mark_rect()
          .encode(x=x_colname, y=y_colname, color='count()'))

chart = heatmap(df_6200309758917209239, *['show_id', 'type'], **{})
chart

import altair as alt
from google.colab import autoviz
df_813656974212399521 = autoviz.get_registered_df('df_813656974212399521')

def heatmap(df, x_colname, y_colname):
  return (alt.Chart(df).mark_rect()
          .encode(x=x_colname, y=y_colname, color='count()'))

chart = heatmap(df_813656974212399521, *['type', 'title'], **{})
chart

import altair as alt
from google.colab import autoviz
df_3385993976212440300 = autoviz.get_registered_df('df_3385993976212440300')

def heatmap(df, x_colname, y_colname):
  return (alt.Chart(df).mark_rect()
          .encode(x=x_colname, y=y_colname, color='count()'))

chart = heatmap(df_3385993976212440300, *['title', 'director'], **{})
chart

import altair as alt
from google.colab import autoviz
df_4082066917006569469 = autoviz.get_registered_df('df_4082066917006569469')

def heatmap(df, x_colname, y_colname):
  return (alt.Chart(df).mark_rect()
          .encode(x=x_colname, y=y_colname, color='count()'))

chart = heatmap(df_4082066917006569469, *['director', 'cast'], **{})
chart

import altair as alt
from google.colab import autoviz
df_1870240864858277418 = autoviz.get_registered_df('df_1870240864858277418')

def swarm_plot(df, value_colname, facet_colname, height=150, width=150):
  value_min, value_max = df[value_colname].min(), df[value_colname].max()
  num_facets = len(df[facet_colname].unique())
  value_colname += ':Q'
  facet_colname += ':N'
  return (alt.Chart(df).mark_circle(size=8)
          .encode(
              x=alt.X('jitter:Q', title=None,
                      axis=alt.Axis(
                          values=[0], ticks=True, grid=False, labels=False)),
              y=alt.Y(value_colname,
                      scale=alt.Scale(domain=[value_min, value_max])),
              color=alt.Color(facet_colname, legend=None),
              column=alt.Column(
                  facet_colname,
                  header=alt.Header(
                      labelAngle=-90, titleOrient='top', labelOrient='bottom',
                      labelAlign='right', labelPadding=3)))
          .properties(height=height, width=width / num_facets)
          .transform_calculate(
              jitter='sqrt(-2*log(random()))*cos(2*PI*random())')  # Box-Muller.
          .configure_facet(spacing=0)
          .configure_view(stroke=None))

chart = swarm_plot(df_1870240864858277418, *['index', 'show_id'], **{})
chart

import altair as alt
from google.colab import autoviz
df_3858089463010908387 = autoviz.get_registered_df('df_3858089463010908387')

def swarm_plot(df, value_colname, facet_colname, height=150, width=150):
  value_min, value_max = df[value_colname].min(), df[value_colname].max()
  num_facets = len(df[facet_colname].unique())
  value_colname += ':Q'
  facet_colname += ':N'
  return (alt.Chart(df).mark_circle(size=8)
          .encode(
              x=alt.X('jitter:Q', title=None,
                      axis=alt.Axis(
                          values=[0], ticks=True, grid=False, labels=False)),
              y=alt.Y(value_colname,
                      scale=alt.Scale(domain=[value_min, value_max])),
              color=alt.Color(facet_colname, legend=None),
              column=alt.Column(
                  facet_colname,
                  header=alt.Header(
                      labelAngle=-90, titleOrient='top', labelOrient='bottom',
                      labelAlign='right', labelPadding=3)))
          .properties(height=height, width=width / num_facets)
          .transform_calculate(
              jitter='sqrt(-2*log(random()))*cos(2*PI*random())')  # Box-Muller.
          .configure_facet(spacing=0)
          .configure_view(stroke=None))

chart = swarm_plot(df_3858089463010908387, *['index', 'type'], **{})
chart

import altair as alt
from google.colab import autoviz
df_8372970496949063063 = autoviz.get_registered_df('df_8372970496949063063')

def swarm_plot(df, value_colname, facet_colname, height=150, width=150):
  value_min, value_max = df[value_colname].min(), df[value_colname].max()
  num_facets = len(df[facet_colname].unique())
  value_colname += ':Q'
  facet_colname += ':N'
  return (alt.Chart(df).mark_circle(size=8)
          .encode(
              x=alt.X('jitter:Q', title=None,
                      axis=alt.Axis(
                          values=[0], ticks=True, grid=False, labels=False)),
              y=alt.Y(value_colname,
                      scale=alt.Scale(domain=[value_min, value_max])),
              color=alt.Color(facet_colname, legend=None),
              column=alt.Column(
                  facet_colname,
                  header=alt.Header(
                      labelAngle=-90, titleOrient='top', labelOrient='bottom',
                      labelAlign='right', labelPadding=3)))
          .properties(height=height, width=width / num_facets)
          .transform_calculate(
              jitter='sqrt(-2*log(random()))*cos(2*PI*random())')  # Box-Muller.
          .configure_facet(spacing=0)
          .configure_view(stroke=None))

chart = swarm_plot(df_8372970496949063063, *['index', 'title'], **{})
chart

import altair as alt
from google.colab import autoviz
df_9203966684256239566 = autoviz.get_registered_df('df_9203966684256239566')

def swarm_plot(df, value_colname, facet_colname, height=150, width=150):
  value_min, value_max = df[value_colname].min(), df[value_colname].max()
  num_facets = len(df[facet_colname].unique())
  value_colname += ':Q'
  facet_colname += ':N'
  return (alt.Chart(df).mark_circle(size=8)
          .encode(
              x=alt.X('jitter:Q', title=None,
                      axis=alt.Axis(
                          values=[0], ticks=True, grid=False, labels=False)),
              y=alt.Y(value_colname,
                      scale=alt.Scale(domain=[value_min, value_max])),
              color=alt.Color(facet_colname, legend=None),
              column=alt.Column(
                  facet_colname,
                  header=alt.Header(
                      labelAngle=-90, titleOrient='top', labelOrient='bottom',
                      labelAlign='right', labelPadding=3)))
          .properties(height=height, width=width / num_facets)
          .transform_calculate(
              jitter='sqrt(-2*log(random()))*cos(2*PI*random())')  # Box-Muller.
          .configure_facet(spacing=0)
          .configure_view(stroke=None))

chart = swarm_plot(df_9203966684256239566, *['index', 'director'], **{})
chart

In [ ]:
#Fehlende Werte überprüfen
Netflix_clean.isna().sum()

title             0
director       2634
cast            825
country         831
duration          3
listed_in         0
description       0
dtype: int64

In [ ]:
#Fehlende Werte in Prozent
(Netflix_clean.isna().sum()/len(Netflix_clean)).apply('{0:.4%}'.format)

title           0.0000%
director       29.9080%
cast            9.3675%
country         9.4357%
duration        0.0341%
listed_in       0.0000%
description     0.0000%
dtype: object

In [ ]:
#Duplikate überprüfen
Netflix_clean.duplicated().sum()

0

### Spalten aufbereiten

In [ ]:
#Unrelevante Spalten entfernen
Netflix_clean = Netflix_Filme.drop(columns=['show_id','date_added','rating','release_year', 'type'])

netflix_titles für Join vorbereiten
Spalten umbennenen:
- country in production_countries
- duration in runtime und 'min' weg
- listed_in in genres
- generell Leerzeichen durch _ ersetzen

In [ ]:
#Leerzeichen durch _ ersetzen
Netflix_clean['title'] = Netflix_clean['title'].str.split('_').str[0]

In [ ]:
#Spalten umbenennen
Netflix_renamed = Netflix_clean.rename(columns={"duration": "runtime", "listed_in": "genres"})

In [ ]:
#Minuten bei runtime entfernen
Netflix_renamed['runtime'] = Netflix_renamed['runtime'].str.split(' ').str[0]

### Datentypen anpassen

In [ ]:
#runtime in float ändern
Netflix_renamed2 = Netflix_renamed.astype({'runtime': float})

In [ ]:
#Überprüfen, ob Datentypen korrekt
Netflix_renamed2.dtypes

title           object
director        object
cast            object
country         object
runtime        float64
genres          object
description     object
dtype: object

### Speicherung des bereinigten Datensatzes

In [ ]:
#Bereinigte Datei abspeichern
Netflix_renamed2.to_csv("netflix_titles_join.csv", index=False)

##Cleaning movie_meta_data.csv

### Überprüfung der Werte im Datensatz

In [ ]:
#Daten einlesen
Movie_Data = pd.read_csv('/content/movie_meta_data.csv')
#Daten anzeigen
Movie_Data

,imdbid,title,akas,year,metascore,imdb user rating,number of imdb user votes,awards,opening weekend,producers,...,casting directors,cast,countries,age restrict,plot,plot outline,keywords,genres,taglines,synopsis
0,120770,A Night at the Roxbury,"Une nuit au Roxbury (France), Movida en el Rox...",1998,26,6,56537,NaN,United States:,"Marie Cantin, Erin Fraser, Amy Heckerling, Ste...",...,Jeff Greenberg,"Will Ferrell, Chris Kattan, Raquel Gardner, Vi...",United States,"Argentina:13, Australia:M, Brazil:14, Canada:P...",Two dim-witted brothers dream of owning their ...,"The Roxbury Guys, Steve and Doug Butabi, want ...","woman-on-top, nightclub, car-accident, 1990s, ...","Comedy, Music, Romance",Score!,NaN
1,132512,At First Sight,"Sight Unseen (United States), Premier regard (...",1999,40,6,12922,NaN,United States:,"Rob Cowan, Roger Paradiso, Irwin Winkler",...,"Kerry Barden, Billy Hopkins, Suzanne Smith","Val Kilmer, Mira Sorvino, Kelly McGillis, Stev...",United States,"Argentina:13, Australia:M, Canada:PG::(Alberta...",A blind man has an operation to regain his sig...,First Sight is true to the title from start to...,"visual-agnosia, brother-sister-relationship, r...","Drama, Romance","Only Love Can Bring You To Your Senses., Scien...",NaN
2,118661,The Avengers,"Chapeau melon et bottes de cuir (France), Mit ...",1998,12,3,40784,"FMCJ Award 1998, Golden Reel Award 1999, Razzi...","United States: $10,305,957, 16 Aug 1998","Susan Ekins, Jerry Weintraub",...,Susie Figgis,"Ralph Fiennes, Uma Thurman, Sean Connery, Patr...",United States,"Argentina:13, Australia:PG, Brazil:10, Canada:...",Two British Agents team up to stop Sir August ...,"British Ministry Agent John Steed, under direc...","good-versus-evil, heroine, evil-man, villain, ...","Action, Adventure, Sci-Fi, Thriller","Mrs. Peel, we're needed., Extraordinary crimes...",NaN
3,215545,Bamboozled,"The Very Black Show (France), It's Showtime (G...",2000,54,6,10373,"Golden Berlin Bear 2001, Black Reel 2001, Imag...",United States:,"Jon Kilik, Spike Lee, Kisha Imani Cameron",...,Aisha Coley,"Damon Wayans, Savion Glover, Jada Pinkett Smit...",United States,"Australia:MA, Finland:K-15, France:Tous public...",A frustrated African-American TV writer propos...,"Dark, biting satire of the television industry...","television-industry, african-american, referen...","Comedy, Drama, Music",Starring the great negroe actors,"In a New York City residence, Pierre Delacroix..."
4,118715,The Big Lebowski,"El gran Lebowski (Spain), O Grande Lebowski (P...",1998,71,8,724388,"Honorable Mention 1998, ACCA 1998, Golden Berl...","United States: $5,533,844, 08 Mar 1998","Tim Bevan, John Cameron, Ethan Coen, Eric Fell...",...,John S. Lyons,"Jeff Bridges, John Goodman, Julianne Moore, St...","United States, United Kingdom","Argentina:16, Argentina:18::(cable rating), Au...","Jeff ""The Dude"" Lebowski, mistaken for a milli...","When ""the dude"" Lebowski is mistaken for a mil...","rug, nihilism, pornographer, bowling-alley, de...","Comedy, Crime, Sport",Hay quienes tratan de ganarse la vida sin move...,A tumbleweed rolls up a hillside just outside ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2853,114924,While You Were Sleeping,"Coma Guy (United States), L'amour à tout prix ...",1995,67,6,90812,"Golden Globe 1996, American Comedy Award 1996,...",NaN,"Steve Barron, Roger Birnbaum, Jonathan Glickma...",...,"Cathy Sandrich Gelfond, Amanda Mackey","Sandra Bullock, Bill Pullman, Peter Gallagher,...",United States,"Argentina:Atp, Australia:PG, Brazil:12, Finlan...",A hopelessly romantic Chicago Transit Authorit...,Nursing a secret and hopeless crush on the han...,"loneliness, unconventional-romance, holiday-se...","Comedy, Drama, Romance",A story about love at second sight.,"Sandra Bullock plays Lucy Ellenore Moderatz, a..."
2854,3011894,Wild Tales,"Les Nouveaux Sauvages (France), Wild Tales (Un...",2014,77,8,174075,"Oscar 2015, BAFTA Film Award 2016, Award of th...",NaN,"Agustín Almodóvar, Pedro Almodóvar, Leticia Cr...",...,Javier Braier,"Darío Grandinetti, María Marull, Mónica Villa,...","Argentina, Spain, France, United Kingdom","Argentina:16, Australia:MA15+, Austria:14, Bra...",Six short stories that explore the extremities...,"The film is divided into six segments. (1) ""Pa...","anthology-film, suicide-by-airplane-crash, rev...","Comedy, Drama, Thriller",We can all lose control,NaN
2855,5362988,Wind River,"Meurtre à Wind River (Canada, French title), S...",2017,73,7,199335,"Saturn Award 2018, American Indian Movie Award...",NaN,"Braden Aftergood, Elizabeth A. Bell, Peter Ber...",...,"Jordan Bass, Lauren Bass","Kelsey Asbille, Jeremy Renner, Julia Jones, Te...","United Kingdom, Canada, United States","Argentina:16, Australia:MA15+, Brazil:16, Cana...",A veteran hunter helps an FBI agent investigat...,"East of Boulder Flats, deep into the vast and ...","investigation, snow, native-american-reservati...","Crime, Drama, Mystery, Thriller","Nothing is harder to track than the truth., Da...","The movie opens at night in a cold, remote Wyo..."
2856,120901,Wrongfully Accused,"Sehr verdächtig (Germany), Unter falschem Verd...",1998,-1,6,23403,Stinker Award 1998,Germany:,"Gary Barber, Warren Carr, Bernd Eichinger, Bob...",...,Karen Rea,"Leslie Nielsen, Richard Crenna, Kelly LeBrock,...","Germany, United States","Argentina:13, Australia:PG, Brazil:12, Canada:...",Ryan Harrison is framed for murder and must pr...,"Ryan Harrison, a violin god, superstar and sex...","warner-bros., sex, violin, one-legged-man, dea...","Action, Comedy, Thriller","It's not just a movie. It's every movie., Some...",World-famous violinist Ryan Harrison (Leslie N...
2857,5742374,You Were Never Really Here,"A Beautiful Day (France), Beautiful Day (Japan...",2017,84,6,101721,"BAFTA Film Award 2019, EDA Female Focus Award ...",Germany:,"Jonathan Ames, Rosa Attab, Jacques Audiard, Su...",...,"Billy Hopkins, Ashley Ingram","Joaquin Phoenix, Dante Pereira-Olson, Larry Ca...","United Kingdom, United States, France","Argentina:16, Australia:MA15+, Austria:16, Bra...","A traumatized veteran, unafraid of violence, t...",Balancing between feverish dreamlike hallucina...,"mother-son-relationship, hammer-as-weapon, chi...","Crime, Drama, Mystery, Thriller",Bring the hammer.,The film opens with Joe (Joaquin Phoenix) in a...

In [ ]:
#Fehlende Werte überprüfen
Movie_Data.isna().sum()

imdbid                          0
title                           0
akas                          206
year                            0
metascore                       0
imdb user rating                0
number of imdb user votes       0
awards                        615
opening weekend              1119
producers                     218
budget                       1234
script department             638
production companies          176
writers                       162
directors                     200
casting directors             717
cast                           52
countries                     180
age restrict                  332
plot                          149
plot outline                  401
keywords                      257
genres                         12
taglines                      602
synopsis                     1006
dtype: int64

In [ ]:
#Fehlende Werte in Prozent
(Movie_Data.isna().sum()/len(Movie_Data)).apply('{0:.4%}'.format)

#Einige Lücken vorhanden,nach dem Joinen eventuell bereinigen

imdbid                        0.0000%
title                         0.0000%
akas                          7.2078%
year                          0.0000%
metascore                     0.0000%
imdb user rating              0.0000%
number of imdb user votes     0.0000%
awards                       21.5185%
opening weekend              39.1533%
producers                     7.6277%
budget                       43.1770%
script department            22.3233%
production companies          6.1582%
writers                       5.6683%
directors                     6.9979%
casting directors            25.0875%
cast                          1.8195%
countries                     6.2981%
age restrict                 11.6165%
plot                          5.2134%
plot outline                 14.0308%
keywords                      8.9923%
genres                        0.4199%
taglines                     21.0637%
synopsis                     35.1994%
dtype: object

In [ ]:
#Duplikate überprüfen
Movie_Data.duplicated().sum()

0

### Spalten aufbereiten

In [ ]:
#Spalten entfernen, die nicht benötigt werden
Movie_Data_clean = Movie_Data.drop(columns=['akas', 'year', 'metascore', 'opening weekend', 'script department', 'writers', 'casting directors', 'age restrict', 'keywords', 'synopsis'])

In [ ]:
#Spalten identisch zu den anderen Datensätzen benennen
Movie_Data_rename=Movie_Data_clean.rename(columns={"taglines": "tageline", "imdb user rating": "imdb_score", "number of imdb user votes": "imdb_votes", "directors": "director", "countries": "country", "imdbid": "imdb_id" })

In [ ]:
#Überprüfen, ob Spalten nun korrekt für joinen
Movie_Data_rename

,imdb_id,title,imdb_score,imdb_votes,awards,producers,budget,production companies,director,cast,country,plot,plot outline,genres,tageline
0,120770,A Night at the Roxbury,6,56537,NaN,"Marie Cantin, Erin Fraser, Amy Heckerling, Ste...","$17,000,000 (estimated)","Broadway Pictures, Paramount Pictures, SNL Stu...",John Fortenberry,"Will Ferrell, Chris Kattan, Raquel Gardner, Vi...",United States,Two dim-witted brothers dream of owning their ...,"The Roxbury Guys, Steve and Doug Butabi, want ...","Comedy, Music, Romance",Score!
1,132512,At First Sight,6,12922,NaN,"Rob Cowan, Roger Paradiso, Irwin Winkler","$60,000,000 (estimated)",Metro-Goldwyn-Mayer,Irwin Winkler,"Val Kilmer, Mira Sorvino, Kelly McGillis, Stev...",United States,A blind man has an operation to regain his sig...,First Sight is true to the title from start to...,"Drama, Romance","Only Love Can Bring You To Your Senses., Scien..."
2,118661,The Avengers,3,40784,"FMCJ Award 1998, Golden Reel Award 1999, Razzi...","Susan Ekins, Jerry Weintraub","$60,000,000 (estimated)","Warner Bros., Jerry Weintraub Productions",Jeremiah S. Chechik,"Ralph Fiennes, Uma Thurman, Sean Connery, Patr...",United States,Two British Agents team up to stop Sir August ...,"British Ministry Agent John Steed, under direc...","Action, Adventure, Sci-Fi, Thriller","Mrs. Peel, we're needed., Extraordinary crimes..."
3,215545,Bamboozled,6,10373,"Golden Berlin Bear 2001, Black Reel 2001, Imag...","Jon Kilik, Spike Lee, Kisha Imani Cameron","$10,000,000 (estimated)","New Line Cinema, 40 Acres & A Mule Filmworks",Spike Lee,"Damon Wayans, Savion Glover, Jada Pinkett Smit...",United States,A frustrated African-American TV writer propos...,"Dark, biting satire of the television industry...","Comedy, Drama, Music",Starring the great negroe actors
4,118715,The Big Lebowski,8,724388,"Honorable Mention 1998, ACCA 1998, Golden Berl...","Tim Bevan, John Cameron, Ethan Coen, Eric Fell...","$15,000,000 (estimated)","Polygram Filmed Entertainment, Working Title F...","Joel Coen, Ethan Coen","Jeff Bridges, John Goodman, Julianne Moore, St...","United States, United Kingdom","Jeff ""The Dude"" Lebowski, mistaken for a milli...","When ""the dude"" Lebowski is mistaken for a mil...","Comedy, Crime, Sport",Hay quienes tratan de ganarse la vida sin move...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2853,114924,While You Were Sleeping,6,90812,"Golden Globe 1996, American Comedy Award 1996,...","Steve Barron, Roger Birnbaum, Jonathan Glickma...","$17,000,000 (estimated)","Hollywood Pictures, Caravan Pictures",Jon Turteltaub,"Sandra Bullock, Bill Pullman, Peter Gallagher,...",United States,A hopelessly romantic Chicago Transit Authorit...,Nursing a secret and hopeless crush on the han...,"Comedy, Drama, Romance",A story about love at second sight.
2854,3011894,Wild Tales,8,174075,"Oscar 2015, BAFTA Film Award 2016, Award of th...","Agustín Almodóvar, Pedro Almodóvar, Leticia Cr...","$3,300,000 (estimated)","British Film Institute, Canal+, Corner Producc...",Damián Szifron,"Darío Grandinetti, María Marull, Mónica Villa,...","Argentina, Spain, France, United Kingdom",Six short stories that explore the extremities...,"The film is divided into six segments. (1) ""Pa...","Comedy, Drama, Thriller",We can all lose control
2855,5362988,Wind River,7,199335,"Saturn Award 2018, American Indian Movie Award...","Braden Aftergood, Elizabeth A. Bell, Peter Ber...","$11,000,000 (estimated)","Acacia Filmed Entertainment, Savvy Media Holdi...",Taylor Sheridan,"Kelsey Asbille, Jeremy Renner, Julia Jones, Te...","United Kingdom, Canada, United States",A veteran hunter helps an FBI agent investigat...,"East of Boulder Flats, deep into the vast and ...","Crime, Drama, Mystery, Thriller","Nothing is harder to track than the truth., Da..."
2856,120901,Wrongfully Accused,6,23403,Stinker Award 1998,"Gary Barber, Warren Carr, Bernd Eichinger, Bob...",NaN,"Morgan Creek Entertainment, Constantin Film",Pat Proft,"Leslie Nielsen, Richard Crenna, Kelly LeBrock,...","Germany, United States",Ryan Harrison is framed for murder and must pr...,"Ryan Harrison, a violin god, superstar and sex...","Action, Comedy, Thriller","It's not just a movie. It's every movie., Some..."
2857,5742374,You Were Never Really Here,6,101721,"BAFTA Film Award 2019, EDA Female Focus Award ...","Jonathan Ames, Rosa Attab, Jacques Audiard, Su...",NaN,"Why Not Productions, Film4, British Film Insti...",Lynne Ramsay,"Joaquin Phoenix, Dante Pereira-Olson, Larry Ca...","United Kingdom, United States, France","A traumatized veteran, unafraid of violence, t...",Balancing between feverish dreamlike hallucina...,"Crime, Drama, Mystery, Thriller",Bring the hammer.

### Datentypen anpassen

In [ ]:
#Datentypen anzeigen lassen
Movie_Data_rename.dtypes

imdb_id                  int64
title                   object
imdb_score               int64
imdb_votes               int64
awards                  object
producers               object
budget                  object
production companies    object
director                object
cast                    object
country                 object
plot                    object
plot outline            object
genres                  object
tageline                object
dtype: object

In [ ]:
#imdb_score in float umwandeln
Movie_Data_clean2 = Movie_Data_rename.astype({'imdb_score': float})

In [ ]:
#imdb_votes in float umwandeln
Movie_Data_clean3 = Movie_Data_clean2.astype({'imdb_votes': float})

In [ ]:
#imdb_id in object umwandeln
Movie_Data_clean4 = Movie_Data_clean3.astype({'imdb_id': object})

In [ ]:
#Datentypen anzeigen lassen
Movie_Data_clean4.dtypes

imdb_id                  object
title                    object
imdb_score              float64
imdb_votes              float64
awards                   object
producers                object
budget                   object
production companies     object
director                 object
cast                     object
country                  object
plot                     object
plot outline             object
genres                   object
tageline                 object
dtype: object

### Speicherung des bereinigten Datensatzes

In [ ]:
#Speichern der gereinigten Daten als csv-Datei
Movie_Data_clean4.to_csv("movie_meta_data_join.csv", index=False)

## Cleaning credits.csv

### Überprüfung der Werte im Datensatz

In [ ]:
#Datensatz laden
credits=pd.read_csv('/content/credits.csv')

#Datensatz anzeigen
credits

,person_id,id,name,character,role
0,3180,tm82169,Sylvester Stallone,"Robert ""Rocky"" Balboa",ACTOR
1,7748,tm82169,Talia Shire,"Adrianna ""Adrian"" Pennino",ACTOR
2,7749,tm82169,Burt Young,Paulie Pennino,ACTOR
3,7750,tm82169,Carl Weathers,Apollo Creed,ACTOR
4,7751,tm82169,Burgess Meredith,Mickey Goldmill,ACTOR
...,...,...,...,...,...
81350,449518,tm1072700,Kayode Olaiya,Uncle Adio,ACTOR
81351,2722717,tm1072700,Tolu Osaile,Sade,ACTOR
81352,2722797,tm1072700,Eniola Oyetola,Officer Meks,ACTOR
81353,866314,tm1072700,Tope Tedela,Officer Jack,ACTOR
81354,1807691,tm1072700,Taiwo Egunjobi,NaN,DIRECTOR

In [ ]:
#Fehlende Werte überprüfen
credits.isna().sum()

person_id        0
id               0
name             0
character    10823
role             0
dtype: int64

In [ ]:
#Fehlende Wert in Prozent
(credits.isna().sum()/len(credits)).apply('{0:.4%}'.format)

person_id     0.0000%
id            0.0000%
name          0.0000%
character    13.3034%
role          0.0000%
dtype: object

In [ ]:
#Duplikate überprüfen
credits.duplicated().sum()

0

### Spalten aufbereiten

In [ ]:
#Spalte löschen die nicht benötigt wird
credits_clean=credits.drop(["person_id"], axis=1)

### Datentypen anpassen

In [ ]:
#Datentypen anzeigen lassen
credits_clean.dtypes

id           object
name         object
character    object
role         object
dtype: object

### Speicherung des bereinigten Datensatzes

In [ ]:
#Speichern der gereinigten Daten als csv-Datei
credits_clean.to_csv("credits_join.csv", index=False)

# Finaler Check vor dem Join

Nach dem alle notwendigen Bereinigungen vorgenommen wurden, prüfen wir abschließend noch einmal, ob die Datensätze nun wirklich alle aneinander angeglichen wurden, damit wir diese im nächsten Schritt miteinander joinen können.
Dazu lassen wir uns nochmal die Datentypen anzeigen, um die Spaltennamen und die Datentypen abgleichen zu können.

## Datentypen

In [ ]:
credits_clean.dtypes

id           object
name         object
character    object
role         object
dtype: object

In [ ]:
screenplay_awards.dtypes

title                                                object
Academy Awards adapted screenplay                    object
Academy Awards original screenplay                   object
BAFTA nominations                                    object
Golden Globe Award for Best Screenplay               object
Writers Guild Awards Winners & Nominees 2020-2013    object
dtype: object

In [ ]:
df_tmdb_5000_clean3.dtypes

budget                   object
genres                   object
id                       object
original_language        object
title                    object
production_companies     object
production_countries     object
runtime                 float64
tagline                  object
tmdb_score              float64
dtype: object

In [ ]:
df_titles_clean2.dtypes

id                       object
title                    object
description              object
runtime                 float64
genres                   object
production_countries     object
imdb_id                  object
imdb_score              float64
imdb_votes              float64
tmdb_score              float64
dtype: object

In [ ]:
Netflix_renamed2.dtypes

title           object
director        object
cast            object
country         object
runtime        float64
genres          object
description     object
dtype: object

In [ ]:
Movie_Data_clean4.dtypes

imdb_id                  object
title                    object
imdb_score              float64
imdb_votes              float64
awards                   object
producers                object
budget                   object
production companies     object
director                 object
cast                     object
country                  object
plot                     object
plot outline             object
genres                   object
tageline                 object
dtype: object

## Inhalte

In [ ]:
Movie_Data_clean4

,imdb_id,title,imdb_score,imdb_votes,awards,producers,budget,production companies,director,cast,country,plot,plot outline,genres,tageline
0,120770,A Night at the Roxbury,6.0,56537.0,NaN,"Marie Cantin, Erin Fraser, Amy Heckerling, Ste...","$17,000,000 (estimated)","Broadway Pictures, Paramount Pictures, SNL Stu...",John Fortenberry,"Will Ferrell, Chris Kattan, Raquel Gardner, Vi...",United States,Two dim-witted brothers dream of owning their ...,"The Roxbury Guys, Steve and Doug Butabi, want ...","Comedy, Music, Romance",Score!
1,132512,At First Sight,6.0,12922.0,NaN,"Rob Cowan, Roger Paradiso, Irwin Winkler","$60,000,000 (estimated)",Metro-Goldwyn-Mayer,Irwin Winkler,"Val Kilmer, Mira Sorvino, Kelly McGillis, Stev...",United States,A blind man has an operation to regain his sig...,First Sight is true to the title from start to...,"Drama, Romance","Only Love Can Bring You To Your Senses., Scien..."
2,118661,The Avengers,3.0,40784.0,"FMCJ Award 1998, Golden Reel Award 1999, Razzi...","Susan Ekins, Jerry Weintraub","$60,000,000 (estimated)","Warner Bros., Jerry Weintraub Productions",Jeremiah S. Chechik,"Ralph Fiennes, Uma Thurman, Sean Connery, Patr...",United States,Two British Agents team up to stop Sir August ...,"British Ministry Agent John Steed, under direc...","Action, Adventure, Sci-Fi, Thriller","Mrs. Peel, we're needed., Extraordinary crimes..."
3,215545,Bamboozled,6.0,10373.0,"Golden Berlin Bear 2001, Black Reel 2001, Imag...","Jon Kilik, Spike Lee, Kisha Imani Cameron","$10,000,000 (estimated)","New Line Cinema, 40 Acres & A Mule Filmworks",Spike Lee,"Damon Wayans, Savion Glover, Jada Pinkett Smit...",United States,A frustrated African-American TV writer propos...,"Dark, biting satire of the television industry...","Comedy, Drama, Music",Starring the great negroe actors
4,118715,The Big Lebowski,8.0,724388.0,"Honorable Mention 1998, ACCA 1998, Golden Berl...","Tim Bevan, John Cameron, Ethan Coen, Eric Fell...","$15,000,000 (estimated)","Polygram Filmed Entertainment, Working Title F...","Joel Coen, Ethan Coen","Jeff Bridges, John Goodman, Julianne Moore, St...","United States, United Kingdom","Jeff ""The Dude"" Lebowski, mistaken for a milli...","When ""the dude"" Lebowski is mistaken for a mil...","Comedy, Crime, Sport",Hay quienes tratan de ganarse la vida sin move...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2853,114924,While You Were Sleeping,6.0,90812.0,"Golden Globe 1996, American Comedy Award 1996,...","Steve Barron, Roger Birnbaum, Jonathan Glickma...","$17,000,000 (estimated)","Hollywood Pictures, Caravan Pictures",Jon Turteltaub,"Sandra Bullock, Bill Pullman, Peter Gallagher,...",United States,A hopelessly romantic Chicago Transit Authorit...,Nursing a secret and hopeless crush on the han...,"Comedy, Drama, Romance",A story about love at second sight.
2854,3011894,Wild Tales,8.0,174075.0,"Oscar 2015, BAFTA Film Award 2016, Award of th...","Agustín Almodóvar, Pedro Almodóvar, Leticia Cr...","$3,300,000 (estimated)","British Film Institute, Canal+, Corner Producc...",Damián Szifron,"Darío Grandinetti, María Marull, Mónica Villa,...","Argentina, Spain, France, United Kingdom",Six short stories that explore the extremities...,"The film is divided into six segments. (1) ""Pa...","Comedy, Drama, Thriller",We can all lose control
2855,5362988,Wind River,7.0,199335.0,"Saturn Award 2018, American Indian Movie Award...","Braden Aftergood, Elizabeth A. Bell, Peter Ber...","$11,000,000 (estimated)","Acacia Filmed Entertainment, Savvy Media Holdi...",Taylor Sheridan,"Kelsey Asbille, Jeremy Renner, Julia Jones, Te...","United Kingdom, Canada, United States",A veteran hunter helps an FBI agent investigat...,"East of Boulder Flats, deep into the vast and ...","Crime, Drama, Mystery, Thriller","Nothing is harder to track than the truth., Da..."
2856,120901,Wrongfully Accused,6.0,23403.0,Stinker Award 1998,"Gary Barber, Warren Carr, Bernd Eichinger, Bob...",NaN,"Morgan Creek Entertainment, Constantin Film",Pat Proft,"Leslie Nielsen, Richard Crenna, Kelly LeBrock,...","Germany, United States",Ryan Harrison is framed for murder and must pr...,"Ryan Harrison, a violin god, superstar and sex...","Action, Comedy, Thriller","It's not just a movie. It's every movie., Some..."
2857,5742374,You Were Never Really Here,6.0,101721.0,"BAFTA Film Award 2019, EDA Female Focus Award ...","Jonathan Ames, Rosa Attab, Jacques Audiard, Su...",NaN,"Why Not Productions, Film4, British Film Insti...",Lynne Ramsay,"Joaquin Phoenix, Dante Pereira-Olson, Larry Ca...","United Kingdom, United States, France","A traumatized veteran, unafraid of violence, t...",Balancing between feverish dreamlike hallucina...,"Crime, Drama, Mystery, Thriller",Bring the hammer.

In [ ]:
Netflix_renamed2

,title,director,cast,country,runtime,genres,description
0,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,90.0,Documentaries,"As her father nears the end of his life, filmm..."
1,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2.0,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,1.0,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,Jailbirds New Orleans,NaN,NaN,NaN,1.0,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2.0,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...
8802,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,158.0,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,Zombie Dumb,NaN,NaN,NaN,2.0,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,88.0,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,88.0,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,111.0,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df_titles_clean2

,id,title,description,runtime,genres,production_countries,imdb_id,imdb_score,imdb_votes,tmdb_score
0,ts300399,Five Came Back: The Reference Films,This collection includes 12 World War II-era p...,51.0,['documentation'],['US'],NaN,NaN,NaN,NaN
1,tm84618,Taxi Driver,A mentally unstable Vietnam War veteran works ...,114.0,"['drama', 'crime']",['US'],tt0075314,8.2,808582.0,8.2
2,tm154986,Deliverance,Intent on seeing the Cahulawassee River before...,109.0,"['drama', 'action', 'thriller', 'european']",['US'],tt0068473,7.7,107673.0,7.3
3,tm127384,Monty Python and the Holy Grail,"King Arthur, accompanied by his squire, recrui...",91.0,"['fantasy', 'action', 'comedy']",['GB'],tt0071853,8.2,534486.0,7.8
4,tm120801,The Dirty Dozen,12 American military prisoners in World War II...,150.0,"['war', 'action']","['GB', 'US']",tt0061578,7.7,72662.0,7.6
...,...,...,...,...,...,...,...,...,...,...
5845,tm1014599,Fine Wine,A beautiful love story that can happen between...,100.0,"['romance', 'drama']",['NG'],tt13857480,6.8,45.0,NaN
5846,tm898842,C/O Kaadhal,A heart warming film that explores the concept...,134.0,['drama'],[],tt11803618,7.7,348.0,NaN
5847,tm1059008,Lokillo,A controversial TV host and comedian who has b...,90.0,['comedy'],['CO'],tt14585902,3.8,68.0,6.3
5848,tm1035612,Dad Stop Embarrassing Me - The Afterparty,"Jamie Foxx, David Alan Grier and more from the...",37.0,[],['US'],NaN,NaN,NaN,10.0
5849,ts271048,Mighty Little Bheem: Kite Festival,"With winter behind them, Bheem and his townspe...",7.0,"['family', 'animation', 'comedy']",[],tt13711094,7.8,18.0,10.0

In [ ]:
df_tmdb_5000_clean3

,budget,genres,id,original_language,title,production_companies,production_countries,runtime,tagline,tmdb_score
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,en,Avatar,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",162.0,Enter the World of Pandora.,7.2
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,en,Pirates of the Caribbean: At World's End,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",169.0,"At the end of the world, the adventure begins.",6.9
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,en,Spectre,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",148.0,A Plan No One Escapes,6.3
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,en,The Dark Knight Rises,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",165.0,The Legend Ends,7.6
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,en,John Carter,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",132.0,"Lost in our world, found in another.",6.1
...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",9367,es,El Mariachi,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",81.0,"He didn't come looking for trouble, but troubl...",6.6
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",72766,en,Newlyweds,[],[],85.0,A newlywed couple's honeymoon is upended by th...,5.9
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",231617,en,"Signed, Sealed, Delivered","[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",120.0,NaN,7.0
4801,0,[],126186,en,Shanghai Calling,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",98.0,A New Yorker in Shanghai,5.7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",25975,en,My Date with Drew,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",90.0,NaN,6.3

In [ ]:
screenplay_awards

,title,Academy Awards adapted screenplay,Academy Awards original screenplay,BAFTA nominations,Golden Globe Award for Best Screenplay,Writers Guild Awards Winners & Nominees 2020-2013
0,A Tree Grows in Brooklyn,+,-,-,-,-
1,Winter s Bone,+,-,-,-,-
2,The Hustler,+,-,-,-,-
3,Leaving Las Vegas,+,-,+,-,-
4,Before Midnight,+,-,-,-,+
...,...,...,...,...,...,...
457,Deadpool,-,-,-,-,+
458,Looper,-,-,-,-,+
459,The Perks of Being a Wallflower,-,-,-,-,+
460,Kingsman Theory of Everything Foxcatcher,-,-,-,-,+
461,One Soldier s Story The Journey of American Sn...,-,-,-,-,+

In [ ]:
credits_clean

              id                name                  character      role
0        tm82169  Sylvester Stallone      Robert "Rocky" Balboa     ACTOR
1        tm82169         Talia Shire  Adrianna "Adrian" Pennino     ACTOR
2        tm82169          Burt Young             Paulie Pennino     ACTOR
3        tm82169       Carl Weathers               Apollo Creed     ACTOR
4        tm82169    Burgess Meredith            Mickey Goldmill     ACTOR
...          ...                 ...                        ...       ...
81350  tm1072700       Kayode Olaiya                 Uncle Adio     ACTOR
81351  tm1072700         Tolu Osaile                       Sade     ACTOR
81352  tm1072700      Eniola Oyetola               Officer Meks     ACTOR
81353  tm1072700         Tope Tedela               Officer Jack     ACTOR
81354  tm1072700      Taiwo Egunjobi                        NaN  DIRECTOR

[81355 rows x 4 columns]